config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :langs
  resources :trailers

  match 'language/:id/trailers', :to => 'langs#trailers', via: :get

end

app/models/lang.rb
class Lang < ActiveRecord::Base
	has_many :trailers
end

app/models/trailer.rb
class Trailer < ActiveRecord::Base
	belongs_to :lang
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  before_filter :cors_preflight_check
  after_filter :cors_set_access_control_headers

  # For all responses in this controller, return the CORS access control headers.

def cors_set_access_control_headers
  headers['Access-Control-Allow-Origin'] = '*'
headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
headers['Access-Control-Request-Method'] = '*'
headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  headers['Access-Control-Max-Age'] = "1728000"
end

# If this is a preflight OPTIONS request, then short-circuit the
# request, return only the necessary headers and return an empty
# text/plain.

def cors_preflight_check
  if request.method == :options
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = '*'
    headers['Access-Control-Max-Age'] = '1728000'
    render :text => '', :content_type => 'text/plain'
  end
end
end

app/controllers/langs_controller.rb
class LangsController < ApplicationController
  before_action :set_lang, only: [:show, :edit, :update, :destroy, :trailers]

  # GET /langs
  # GET /langs.json
  def index
    @langs = Lang.all
  end

  def trailers
    @trailers = @lang.trailers
    respond_to do |format|
      format.html { redirect_to @lang, notice: 'Lang was successfully created.' }
      format.json { render json: @trailers }
    end
  end

  # GET /langs/1
  # GET /langs/1.json
  def show
  end

  # GET /langs/new
  def new
    @lang = Lang.new
  end

  # GET /langs/1/edit
  def edit
  end

  # POST /langs
  # POST /langs.json
  def create
    @lang = Lang.new(lang_params)

    respond_to do |format|
      if @lang.save
        format.html { redirect_to @lang, notice: 'Lang was successfully created.' }
        format.json { render :show, status: :created, location: @lang }
      else
        format.html { render :new }
        format.json { render json: @lang.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /langs/1
  # PATCH/PUT /langs/1.json
  def update
    respond_to do |format|
      if @lang.update(lang_params)
        format.html { redirect_to @lang, notice: 'Lang was successfully updated.' }
        format.json { render :show, status: :ok, location: @lang }
      else
        format.html { render :edit }
        format.json { render json: @lang.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /langs/1
  # DELETE /langs/1.json
  def destroy
    @lang.destroy
    respond_to do |format|
      format.html { redirect_to langs_url, notice: 'Lang was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lang
      @lang = Lang.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lang_params
      params.require(:lang).permit(:name, :title, :aka)
    end
end

app/controllers/trailers_controller.rb
class TrailersController < ApplicationController
  before_action :set_trailer, only: [:show, :edit, :update, :destroy]

  # GET /trailers
  # GET /trailers.json
  def index
    @trailers = Trailer.all
  end

  # GET /trailers/1
  # GET /trailers/1.json
  def show
  end

  # GET /trailers/new
  def new
    @trailer = Trailer.new
  end

  # GET /trailers/1/edit
  def edit
  end

  # POST /trailers
  # POST /trailers.json
  def create
    @trailer = Trailer.new(trailer_params)

    respond_to do |format|
      if @trailer.save
        format.html { redirect_to @trailer, notice: 'Trailer was successfully created.' }
        format.json { render :show, status: :created, location: @trailer }
      else
        format.html { render :new }
        format.json { render json: @trailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trailers/1
  # PATCH/PUT /trailers/1.json
  def update
    respond_to do |format|
      if @trailer.update(trailer_params)
        format.html { redirect_to @trailer, notice: 'Trailer was successfully updated.' }
        format.json { render :show, status: :ok, location: @trailer }
      else
        format.html { render :edit }
        format.json { render json: @trailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trailers/1
  # DELETE /trailers/1.json
  def destroy
    @trailer.destroy
    respond_to do |format|
      format.html { redirect_to trailers_url, notice: 'Trailer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trailer
      @trailer = Trailer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trailer_params
      params.require(:trailer).permit(:name, :desc, :youtube_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/langs_helper.rb
module LangsHelper
end

app/helpers/trailers_helper.rb
module TrailersHelper
end

app/views/langs/_form.html.erb
<%= form_for(@lang) do |f| %>
  <% if @lang.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lang.errors.count, "error") %> prohibited this lang from being saved:</h2>

      <ul>
      <% @lang.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :aka %><br>
    <%= f.text_field :aka %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/langs/edit.html.erb
<h1>Editing Lang</h1>

<%= render 'form' %>

<%= link_to 'Show', @lang %> |
<%= link_to 'Back', langs_path %>

app/views/langs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Langs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Aka</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @langs.each do |lang| %>
      <tr>
        <td><%= lang.name %></td>
        <td><%= lang.title %></td>
        <td><%= lang.aka %></td>
        <td><%= link_to 'Show', lang %></td>
        <td><%= link_to 'Edit', edit_lang_path(lang) %></td>
        <td><%= link_to 'Destroy', lang, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lang', new_lang_path %>

app/views/langs/new.html.erb
<h1>New Lang</h1>

<%= render 'form' %>

<%= link_to 'Back', langs_path %>

app/views/langs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lang.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @lang.title %>
</p>

<p>
  <strong>Aka:</strong>
  <%= @lang.aka %>
</p>

<%= link_to 'Edit', edit_lang_path(@lang) %> |
<%= link_to 'Back', langs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nmts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trailers/_form.html.erb
<%= form_for(@trailer) do |f| %>
  <% if @trailer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trailer.errors.count, "error") %> prohibited this trailer from being saved:</h2>

      <ul>
      <% @trailer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :youtube_id %><br>
    <%= f.text_field :youtube_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trailers/edit.html.erb
<h1>Editing Trailer</h1>

<%= render 'form' %>

<%= link_to 'Show', @trailer %> |
<%= link_to 'Back', trailers_path %>

app/views/trailers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trailers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Youtube</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trailers.each do |trailer| %>
      <tr>
        <td><%= trailer.name %></td>
        <td><%= trailer.desc %></td>
        <td><%= trailer.youtube_id %></td>
        <td><%= link_to 'Show', trailer %></td>
        <td><%= link_to 'Edit', edit_trailer_path(trailer) %></td>
        <td><%= link_to 'Destroy', trailer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trailer', new_trailer_path %>

app/views/trailers/new.html.erb
<h1>New Trailer</h1>

<%= render 'form' %>

<%= link_to 'Back', trailers_path %>

app/views/trailers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trailer.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @trailer.desc %>
</p>

<p>
  <strong>Youtube:</strong>
  <%= @trailer.youtube_id %>
</p>

<%= link_to 'Edit', edit_trailer_path(@trailer) %> |
<%= link_to 'Back', trailers_path %>